name: deploy site

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy Website 
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        host: ${{ secrets.HOSTS }}
        username: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        privateKey: ${{ secrets.PRIKEY }}
        command: |
              cd /srv/site
              cd honestperson
              git remote update
              git checkout production
              git pull origin production
              composer du
              composer install
              php artisan optimize:clear  
